// Code generated by schema-generate. DO NOT EDIT.

package output

// Hobbies 
type Hobbies struct {
  Indoor []string `json:"indoor,omitempty"`
  Outdoor []string `json:"outdoor,omitempty"`
}

// RecordOfEmployee 
type RecordOfEmployee struct {
  Age float64 `json:"age,omitempty"`
  Hobbies *Hobbies `json:"hobbies,omitempty"`
  Id float64 `json:"id,omitempty"`
  Name string `json:"name,omitempty"`
}
