// Code generated by schema-generate. DO NOT EDIT.

package output

// Base 
type Base struct {
  Base interface{} `json:"@base,omitempty"`
  Id interface{} `json:"@id,omitempty"`
}

// NcAmountType 
type NcAmountType struct {
  NcAmount interface{} `json:"nc:Amount,omitempty"`
  NcCurrency interface{} `json:"nc:Currency,omitempty"`
}

// NcIdentificationType 
type NcIdentificationType struct {
  NcIdentificationID interface{} `json:"nc:IdentificationID,omitempty"`
}

// data 
type data struct {
  NcAmount interface{} `json:"nc:Amount,omitempty"`
  NcCurrency interface{} `json:"nc:Currency,omitempty"`
  NcCurrencyCode interface{} `json:"nc:CurrencyCode,omitempty"`
  NcIdentificationID interface{} `json:"nc:IdentificationID,omitempty"`
  NcVehicle interface{} `json:"nc:Vehicle,omitempty"`
  NcVehicleAxleQuantity interface{} `json:"nc:VehicleAxleQuantity,omitempty"`
  NcVehicleIdentification interface{} `json:"nc:VehicleIdentification,omitempty"`
  NcVehicleMSRPAmount interface{} `json:"nc:VehicleMSRPAmount,omitempty"`
}
