// Code generated by schema-generate. DO NOT EDIT.

package output

// PackageList 
type PackageList struct {
}

// element 
type element struct {
  Abandoned *PackageList `json:"abandoned,omitempty"`
  Name string `json:"name"`
}
